export const dateSeed=[
    {   
        id:1,
        date:1,
        events:[
           
        ]    
    },{
          id:2,
          date:2,
          events:[
           
        ]   
    },{
        id:3,
        date:3,
        events:[]    
    },{
          id:4,
          date:4,
        events:[]    
    },{
          id:5,
          date:5,
        events:[]    
    },{
          id:6,
          date:6,
          events:[
           
        ]     
    },{
          id:7,
          date:7,
        events:[]    
    },{
          id:8,
          date:8,
        events:[]    
    },{
          id:9,
          date:9,
        events:[]    
    },{
          id:10,
          date:10,
        events:[]    
    },{
          id:11,
          date:11,
        events:[]    
    },{
          id:12,
          date:12,
        events:[]    
    },{
          id:13,
          date:13,
        events:[]    
    },{
          id:14,
          date:14,
        events:[]    
    },{
          id:15,
          date:15,
        events:[]    
    },{
          id:16,
          date:16,
        events:[]    
    },{
          id:17,
          date:17,
        events:[]    
    },{
          id:18,
          date:18,
        events:[]    
    },{
          id:19,
          date:19,
        events:[]    
    },{
          id:20,
          date:20,
        events:[]    
    }
    ,{
          id:21,
          date:21,
        events:[]    
    },{
          id:22,
          date:22,
        events:[]    
    },{
          id:23,
          date:23,
        events:[]    
    },{
          id:24,
          date:24,
        events:[]    
    },{
          id:25,
          date:25,
        events:[]    
    },{
          id:26,
          date:26,
        events:[]    
    },{
          id:27,
          date:27,
        events:[]    
    },{
          id:28,
          date:28,
        events:[]    
    },{
          id:29,date:29,
        events:[]    
    },
    {
          id:30,date:30,
        events:[]    
    }
]
export const timeSeed =['1am','2am','3am','4am','5am','6am','7am','8am','9am','10am','11am','12pm','1pm','2pm','3pm','4pm','5pm','6pm','7pm','8pm','9pm','10pm','11pm']